name: mcbac-env
channels:
  - conda-forge
  - wpk-nist
dependencies:
  - python=3.8
  # because using scm versioning
  - setuptools>=38.4
  - numpy
  - scipy
  - pandas
  - xarray
  - pymatgen
  - gemmi
  # cli
  - Click
